// v.1.1.2 =======================================================
// app/layout.tsx
// import "./globals.css"; // สไตล์รวม
// import { LiffProvider } from "./contexts/LiffContext"; // นำเข้า LiffProvider

// export const metadata = {
//   title: "LIFF Camera App",
//   description: "LINE LIFF Camera example with Next.js App Router",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body>
//         <LiffProvider>{children}</LiffProvider>
//       </body>
//     </html>
//   );
// }
// v.1.1.2 =======================================================

// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Camera App v1.0",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
